import {makeBookmarkFlat} from '../helpers';
import {Category} from '../typings';
import {CreatorPostDto} from '../typings/typings.v2';

export const Constants = {
  bookmarks: makeBookmarkFlat(
    require('./../assets/bookmark.json') as Category[],
  ),
  categories: (require('./../assets/bookmark.json') as Category[]).map(d => ({
    label: d.category,
    value: d.category,
  })),
  directoryName: 'coomer',
  bunkrDirectory: 'bunkr',
  videoExtensions: [
    '.mp4',
    '.mov',
    '.avi',
    '.mkv',
    '.wmv',
    '.flv',
    '.webm',
    '.m4v',
  ],
  imageExtensions: ['.jpg', '.jpeg'],
};

export const defaultPosts: any[] = [
  {
    id: '927894587',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '*Hot Tub + Shower Fuck*\n\nI can’t get enough of @hattrickz91!..',
    content:
      '*Hot Tub + Shower Fuck*\n\nI can’t get enough of @hattrickz91! What started out as relaxing in the hot tub turned into me taking his huge dick right in the backyard. Then we went to the shower to wash off, he had me on my knees and filled up my pussy with a fat load 😏',
    embed: {},
    shared_file: false,
    added: '2024-03-24T13:46:27.607693',
    published: '2024-02-09T15:25:41',
    edited: null,
    file: {
      name: '0hmnmp7xkq0czjngrns7o_source.mp4',
      path: '/f3/a2/f3a20256feba7d3ee270920188d89dbd3ca11fae32b1d383a9ff0c562ba6e8c1.mp4',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
  {
    id: '926959383',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '*BBC ANAL CREAMPIE*\n\nI had so much fun with @flightlifexxx i..',
    content:
      '*BBC ANAL CREAMPIE*\n\nI had so much fun with @flightlifexxx in LA. While we were fucking, he couldn’t help but put a finger in my ass- which obviously led to me taking his thick cock in my ass too 🤤 I fucking love anal, and he loved cumming in my asshole 😈',
    embed: {},
    shared_file: false,
    added: '2024-03-24T13:55:52.894008',
    published: '2024-02-08T21:36:37',
    edited: null,
    file: {
      name: '0hmmrry5tg66acmeu1tqn_source.mp4',
      path: '/62/e6/62e642a6204901da7de3084708a45accad91d1defd54c338c3fea39b47e57d0f.mp4',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
];

// const url = [
//   'https://c6.coomer.su/data/85/e3/85e39d1b6b1cb3dd18a509fd8db979e4e91fb784cbe4814d85ce6830c47766d8.mp4?f=2022-07-13 20 Afternoon delight 🌞♥️ (OnlyFans) 1716805989165.mp4',
//   'https://c5.coomer.su/data/e1/3f/e13f3f5dce59f10dc78f1aac0d432a92b969f2bdf5c68732ad9e4a959bbb4756.mp4?f=2022-07-10 21 Ass & titties, ass & titties 🍒 🍑 (OnlyFans) 1716805989948.mp4',
//   'https://c2.coomer.su/data/e9/b2/e9b2450c9c20e9e474286891dae3a5c6cd8c2562d287840eaf27341272cf43de.mp4?f=2022-07-10 21 Ass & titties, ass & titties 🍒 🍑 (OnlyFans) 1716805989954.mp4',
//   'https://c3.coomer.su/data/d1/6c/d16c6cbe7b7b166efcedafb6944dbd0d2d35a4db965f92307a9eee7268e1bb7e.mp4?f=2022-07-05 16 A little yoga video I made (half clothed/half nude) Enjoy :) (OnlyFans) 1716805990406.mp4',
//   'https://c3.coomer.su/data/84/2b/842b8e16bbbd5ec363d9283a17c2cfea903f545b31d01f1bebbd00a137934ea1.mp4?f=2022-07-01 18 Had a fun Skype session today 😛 (OnlyFans) 1716805991887.mp4',
//   'https://c4.coomer.su/data/e2/70/e2704524cdf72974449087260d777c9ef076c1e32774d55a00b7824f19592ddd.mp4?f=2022-06-26 00 I love kissing girls 👯‍♀️ Check your inbox for the full vide.. (OnlyFans) 1716805992579.mp4',
//   'https://c5.coomer.su/data/e6/d8/e6d890fba3d4a144dbdd21d48da99af265c35be1c4fb5de0f2f684f229f1db2b.mp4?f=2022-06-21 18 Do you like it when I rub lotion all over my body? 🤤🥰 (OnlyFans) 1716805994484.mp4',
//   'https://c1.coomer.su/data/3a/4c/3a4c048daf8173d14bc4c2f90327cf09dddb671cc89bac3027454b62b6b32224.mp4?f=2022-06-17 18 Imagine this: I’m the girl next door that you want to fuck 😉.. (OnlyFans) 1716805993776.mp4',
//   'https://c4.coomer.su/data/6f/36/6f361ec507d90dd6ea6cb0d4d1d2b05e49609cbc4c064aea3ee28c379f6078af.mp4?f=2022-06-11 18 🥚Let’s pretend we’re at a strip club today on my OnlyFans 😋 .. (OnlyFans) 1716805995694.mp4',
//   'https://c6.coomer.su/data/cf/9e/cf9e0697ed15da36a0215704474d00e45418cdb3dab7654cb65fb753625608f7.mp4?f=2022-05-31 15 I usually like to post more of my bootay 🍑, but come on, it’.. (OnlyFans) 1716805998051.mp4',
//   'https://c4.coomer.su/data/69/34/6934cefa4e463762bc64f72a0efc5dd68ff7694cae635bbee0f2f9f433153eaf.mp4?f=2022-05-30 19 Boobies are here for two reasons: 1) feeding & 2) playing wi.. (OnlyFans) 1716805998317.mp4',
//   'https://c3.coomer.su/data/2e/fe/2efe1d27d739c2045087b0403388555e3ec5db3e20b6de0bf08269f05c09d336.mp4?f=2022-05-24 21 I need help getting out of these handcuffs so I can touch my.. (OnlyFans) 1716805999374.mp4',
// ];

export const exportedModels: string[] = [
  'libideux',
  'megy.feet',
  'redwhiteandnude',
  'timntony',
  'alunavita',
  'CleoAlice',
  'Sophie-Dom-98',
  'kinkyagegapcpl',
  'gelatosunrise',
  'avaxsmalls',
  'hegota1dick',
  'ideve',
  'missgem000',
  'lane217',
  'jbswg_diary',
  'charmdaze',
  'alexisyogafeet2',
  'st0ned-and-b0ned',
  'hotcoupleonshowvip',
  'thesexygoddessmrspunk',
  'mrshnylons',
  'blueeyedbabie97',
  'karina_hot_wife',
  'tropicalpassion',
  'lululacy',
  'mrsenglewood',
  'Teenmelanie',
  'Milf_Goddess',
  'yourfinalgirl',
  'BunnyCritter',
  'amber_honeybunny',
  'Luanab',
  'Tinylily1',
  'Yummy_Girl',
  'hairyblondie',
  'hairysarasweden',
  'theonehairyfairy',
  'jadynnstone',
  'onlymikewilliams',
  'greatmoongirl0',
  'kurvy_kat',
  'rayeroze',
  'bigbootybaileyvip',
  'welcometothesmokeshow',
  'mysteriousmagsxoxo',
  'adorableamypee',
  'Nicole_6969',
  'brynnbaybee',
  'SophiesWetWorld',
  'nJoy_Anna',
  'we69we69',
  'lovelylavenderjoy',
  'mark_rosie_bg',
  'stop_hammerzeit',
  'amazonaria',
  'marcitoes23x',
  'marcitoes23',
  'stinkysweetsole',
  'goddessindicawynter',
  'gabrielagalore',
  'kitcat456',
  'misslacylennon',
  'contentcandytv',
  'toesbeforebros_lite',
  'toesbeforebros_',
  'almanegrasexe',
  'hiimbee',
  'siennarae_x',
  'gigi.patsy',
  'myamorgan2000',
  'rawhunnyy',
  'teeny3',
  'senpaisslut',
  'vitacelestine',
  'elivalovepremium',
  'avamoorex',
  'leiase',
  'ricoreyes',
  'mrsrakks',
  'jessycat04',
  'hot_mom_adventurebrit3',
  'eerikamikaelabasic',
  'itsivannababe',
  'nefry92',
  'skyebluegfe',
  'puckbunny5',
  'xratedswingers',
  'oooooooohgodent',
  'brandinoppv',
  'loz2807_noppv',
  'goddess_natalia69',
  'DuoLure',
  'the-wonderland',
  'kinkyfae',
  'sunshines.playground',
  'cassieclaire',
  'czechqueenof',
  'tootsiepopt',
  'lorraineedwards91',
  'cuckoldcoupleplus1',
  'bbwsilverbunny',
  'daniashley',
  'sinnersworldxxx',
  'isiscristinepremium',
  'br000k33xo',
  'br000k33',
  'dawndesireph',
  'sumchloevip',
  'chloxxhillvip',
  'misspenny93',
  'pantyhose_princess99',
  'islandbrooke',
  'beautiful21chaos',
  'hotwifejadeli',
  'mianoppv',
  'LilianeHart',
  'yourpeeprincess',
  'melody_katt',
  'hotgirlmeg0',
  'thesixfigurerebel',
  'alicekacy722',
  'onlysockies',
  'whispergirl',
  'angelrawww',
  'jayjademoon',
  'JayJadeMoon',
  'shugah_boogah',
  'Shugah_Boogah',
  'churchwifey_kk',
  'PiercedNoodle',
  'ellynora',
  'alkethadea',
  'bigduchvip',
  'secretnymphomaniac',
  'minalf',
  'misty.wet',
  'purrfectvixen_xo',
  'Chincherri',
  'emilytheladybug',
  'Emilytheladybug',
  'peachfulvibes-ppv',
  'peachfulvibes',
  'frenchava',
  'alicevalentine',
  'aprilfeelix',
  'curves4daze',
  'daisy.sky.23',
  'beronniexox',
  'princessbedford',
  'watashiwajosefina',
  'vixenshelby',
  'Vixenshelby',
  'lactationprincess',
  'cutemiasophie',
  'queenb_natalie',
  'pretty_mime',
  'starrelove69',
  'zoeyziptie',
  'ShyGothExhib',
  'skylightlife',
  'keira_xxxxxx',
  'ceressinclair',
  'thespicyblueymom',
  'kinky-bitch69',
  'fitkatiekarr',
  'katiekarr',
  'bunnisluut',
  'goddessmarcy',
  'blondifeet',
  'maccypeachesvip',
  'gynarchygoddess',
  'unawkward_silence',
  'bratbaby710',
  'dom.maiden420',
  'fitxmama',
  'the444thday',
  'supersplash99',
  'koriayn',
  'injoybacon-premium',
  'sophiaweb',
  'curvvyyb',
  'belleanddansfans',
  'bbt88',
  'JessieAndJackson',
  'high_hoe',
  'leojamie',
  'youlikewhatyousee',
  'floranerussell',
  'amieadams_unlocked',
  'jjames70779191',
  'jessicaperez',
  'Demure_Whore',
  'yasmeenaxxx',
  'yasmeena',
  'fabianotheep',
  'stella_bella_xoxo',
  'sammiecee',
  'shoe_lovers',
  'nadjazag',
  'kittykatrina21',
  'bubblystephxo',
  'metal_kitten666',
  'lilyhoneybee',
  'its_susannuh',
  'brooklynspringvalley',
  'jucielucie89',
  'virtuousgirljoy',
  'legsnlingerie',
  'luna-jane',
  'sassybabyy2',
  'emilialilyjoness',
  'galateaof',
  'mareesly',
  'Mareesly',
  'lacykelly',
  'lilyalcott',
  'elizhawks10',
  'laylaadraya',
  'officialhtownliv',
  'lola_blaize',
  'dawgette',
  'classiccardad',
  'sheababy420vip',
  'belle2525',
  'marissasweet',
  'chubbyred444',
  'chubbychiquita',
  'ickyy',
  'gummyhead00',
  'milavolker',
  'Milavolker',
  'stuffybunnyloveofficial',
  'fchdommes',
  'joycezarza',
  'dilamete',
  'lolapeachvip',
  'thetiffanyflowersvip',
  'korachubbsy',
  'DanishDesire',
  'dutchblondeprincess',
  'donkeypawg',
  'Donkeypawg',
  'backdoorgf',
  'redsdelight',
  'Redsdelight',
  'lusty.border',
  'spicytender2',
  'nurseluvs2sqrt',
  'rawrawitssarah',
  'missysugar',
  'drinkswithdd',
  'forrestnimmph',
  'blondefoxsilverfox',
  'yourhotm.f',
  'jennysfeet',
  'BblueDdream',
  'worthlessholes',
  'emilyglass696',
  'hourglassleigh',
  'glassimpulse',
  'Lactatingmom',
  'LactatingDaisy',
  'aprilfoxx',
  'allies2004',
  'aozora_vip',
  'aozora_x',
  'freakslutsage',
  'evahans',
  'emypawg',
  'Blonde_whore',
  'leemadison',
  'justmia.of',
  'missx_x_mg',
  'missnerdydirty',
  'maddiebubz',
  'Maddiebubz',
  'zoeyuso',
  'ZoeyUso',
  'Pregodelight',
  'tara.soblban',
  'emmyjoee',
  'jaybbgirl',
  'chantelleh23',
  'chantelleh2233',
  'poison_ivee',
  'giulianacabrazia2',
  'bel_blondie1',
  'allnaturalaurora',
  'luxlo',
  'maryjanecame',
  'sweetheartxo21',
  'rose.uk.vip',
  'itsonlyfangs',
  'nadiafoxx69',
  'feyafernn',
  'feyafern',
  'softnspooky',
  'jasminerosexo_',
  'bbwlaladelilah',
  'laladelilah',
  'amwf_alice',
  'xchandlerknight',
  'hannahlouu',
  'kimjett',
  'justhavingfunwithlife',
  'aprilmaexox',
  'delilahboopity',
  'candicecream37',
  'juicybabydoll',
  'lizzsweet6',
  'MilkyMama1',
  'milkymama04',
  'KelceCarter',
  'chelle0069',
  'Chelle0069',
  'Dreamaliciousxxx',
  'MissSugarTits96',
  'midnightmamaaa',
  'bumpinbaccas',
  'lustfeed',
  'dragunball',
  'thelittlered',
  'babyrivsvip',
  'audreyandsadie',
  'jeanmarieexo',
  'vballchick888',
  'lilac_lov3',
  'smokeyvip',
  'ava_alex',
  'nycbisexcouplepremium',
  'nymferatu',
  'moe_kkash',
  'JonathanWolfe',
  'bigeyesxoxo',
  'liliafourtwenty',
  'diet_marshmallow',
  'PiajTiaj',
  'jennaxoverdose',
  'sucha_goodgirl',
  'natural_emma_',
  'realgiantessa',
  'giantess_ashton',
  'giantessa',
  'AstraDisaster',
  'backwoods1barbie',
  'BackwoodsEmm',
  'sleepyxxxsarah',
  'fitnsmall',
  'naotemasbby',
  'immydaddysslt',
  'goodbettersex',
  'c.rina',
  'bealz',
  'kittyyy_cait',
  'kalliefreya',
  'd_peachyyy',
  'clara_dee',
  'MistressThrope',
  'ladyinfirst',
  'Ladyinfirst',
  'thecoupleyouwatch',
  'purepleasure',
  'calitafire',
  'alisswonderlandd',
  'prettysadiereed',
  'PrettySadieReed',
  'barewithmargot',
  'sexymissme',
  'SexyMissMe',
  'fruitsforbats',
  'aragnespicy',
  'doremiaxx',
  'lil_cakebaby',
  'raven-graves',
  'urgothgf.exe',
  'slaveclairebear',
  'SlaveClaireBear',
  'annikashae',
  'lunabenna',
  'oooops__',
  'cloverfae',
  'steverickz',
  'flowerbrat',
  'domina.gray.xxx',
  'digiraww',
  'beldots',
  'pavemiau',
  'lolaleevip',
  'peeing4u',
  'anakakkonen',
  'margotdiamond',
  'autumnbuttons',
  'syndica',
  'marleymathers',
  'MarleyMathers',
  'sadieandsmut',
  'chloekreams',
  'AugustZoldyck',
  'cait_linh',
  'shackled.divinity',
  'MissDemeanour',
  'likes2shareinsocal',
  'itsmeemily96',
  'castingcurvy',
  'lillymcxxx',
  'urgaystonergf666',
  'mimi_flowers_premium',
  'thesesweetfeet20',
  'mrs.reps.o.g',
  'mymazikeen',
  'summerdayzzze',
  'laheldoll',
  'pastel_waifu',
  'sallysecret',
  'kinkycastle',
  'emmie.sg',
  'lolarosexxx',
  'cecenicolesmith',
  'littlethicklily',
  'katiesweety',
  'torrencelust.vip',
  'thelifeofthelioness',
  'delilahbrooke',
  'domslutfucker',
  'littlelillyfckslut',
  'MasterandMargarita',
  'briarriley',
  'Elleslovexoxo',
  'KinkyEmma',
  'kinkyemma',
  'stardust.angel',
  'mini.mimiiii',
  'krystaltopazxxx',
  'bridgetbishopxxx',
  'aurorafiend',
  'jandk92',
  'cutewife0',
  'muun_grl',
  'brooksariel',
  'brucbb',
  'msberry',
  'link_taylor',
  'ThtHorrorgirl36',
  'bethany_spiby',
  'bigassvenus',
  'sapphireonfire',
  'lostodg',
  'malicejade',
  'Malice_Jade',
  'ravenivee',
  'CoquettePanda',
  'fatherlessavery',
  'erikaxstacy',
  'faekitti',
  'mayaportugal',
  'baby_violet420',
  'sarahs_peach',
  'lilredvelvettt',
  'lilredvelvet',
  'baaboobeebop69',
  'messyaftermidnight',
  'margaritabootyvip',
  'finnismine',
  'xkittycatgirlx',
  'goddessrosex',
  'couplemodern',
  'hollyrivers',
  'thorriandjax',
  'ThorriandJax',
  'JaxWorld',
  'oliviabaylive',
  'passion_couple',
  'cybertits',
  'goddessfreyabbw',
  'bunnybarnett',
  'domestickatevip',
  'hopepenetration',
  'harmonierain',
  'helenrofficial',
  'krcphotos1',
  'hotpaigesummers',
  'slavebc',
  'masterslbs',
  'masterslbsvip',
  'mastersLBS',
  'sophiasubxx',
  'puddlesvip',
  'dawn24theshowcouple',
  'yantastik',
  'aurorab987',
  'justviolet',
  'the_ilybabe',
  'librarosebud',
  'couplakinks',
  'beauty_busty',
  'aurora.luxe',
  'b1gtheo',
  'bimbobabey',
  'LovelyBea',
  'juicyygracee',
  'myrealgirlfriend',
  'princess_bubblebuttt',
  'thethickreaper',
  'Kukinacosta',
  'WitchyHime',
  'parannanza1',
  'Parannanza',
  'WhiteGoldGoddess',
  'toyst',
  'TOYST',
  'mylilgirl',
  'princessmollie',
  'PrincessMollie',
  'lolasplashqueen',
  'GoddessFloraSparks',
  'badlilbunny23',
  'LittleOliveLove',
  'aubreysvault',
  'siobhangraves1',
  'ethereallovebug',
  'dankpizza',
  'aurorashaw69',
  'rubypeachxo',
  'lexyreptiles',
  'jaydebelle',
  'thicladybug',
  'j0ivy',
  'heidi_lee_bocanegra',
  'kinkydomkitty91',
  'livvyblaire',
  'michellexxxc',
  'playtimecosplay',
  'kisicaxx',
  'desbaby_1995',
  'sexysarabeevip',
  'yuki.nky',
  'mistressesmeralda',
  'tammaragold',
  'isaluvbbw',
  'debraquinn',
  'kitsy-vixen',
  'Nataliamann',
  'imkerrie',
  'jennifear93',
  'celestenoir',
  'nakieplantlady',
  'summerjust18',
  'yourcora',
  'latexnchill',
  'tastytaurustoes',
  'meowkauwu',
  'yourshamelessplug',
  'snomarie69',
  'lilykoti',
  'valeriewhitebby',
  'hellomoonli',
  'bdsmbelle',
  'spankmyassredd',
  'MeltyMutt',
  'kinky_kouple_aa',
  'Nataliebrown',
  'LilyPink',
  'lisawildlove',
  'Elizabeth_Shameless',
  'thereal_irish_cay-wild',
  'herbgardennnn',
  'zaydarose',
  'babygirlnewmoon',
  'one_punch_cum',
  'skyesharpvip',
  'bunnydathug',
  'norarosejeanxx',
  'norarosejean',
  'UndyneAra',
  'dctrousersnakevip',
  'milkymamaxoxo',
  'milkymamaxo',
  'mommablondebombshell',
  'amber_hotwife',
  'redwildcat',
  'greencatfromhell',
  'Nastya02',
  'yourhornyneighbor',
  'wubzy',
  'lacey_royce',
  'lilymariemfc',
  'Polarmi',
  'babybloo',
  'gothiccbabi',
  'faridahaniya',
  'thiccghosty',
  'cathycrownof',
  'laylagrace.3',
  'u418914783',
  'daisydestin',
  'sweetchelseak',
  'walking.in.the.forest',
  'indiegirl666',
  'SweetSophie25',
  'Hetrainsherass',
  'roziekatz',
  'annemariekatz',
  'xangelrainx',
  'InNeedOfTheFist',
  'darlingdaisiess',
  'driane_de_DKN',
  'Bellasworld4u',
  'dark_mistress5',
  'Babygoat_polo_',
  'beccaksoles',
  'yummie_bunnie',
  'kylie_coco',
  'cavalierifeet',
  'kisscat_studio',
  'luciferbutfemale',
  'the_foot_dungeon',
  'haleyquinnla',
  'scarlettshoward',
  'ivorylux2',
  'thebellamkay',
  'therealselenaloca',
  'yourbigfatfriend',
  'bustybubblz',
  'helloella',
  'LilMamaSel',
  'MilkyxxSweet',
  'mika_mae',
  'Mika_mae',
  'Charlotte_Payne',
  'yourfantasy6190',
  'kitty_flamez',
  'jmommat81',
  'eve-apple',
  'opal.stardust',
  'princessbabybratx',
  'niamhhhh',
  'courtneycassanova.vip',
  'lucialatinagomez',
  'luckymotherfker',
  'federicacorona',
  'playgroundtaboo',
  'gypssai',
  'piperblush',
  'courtneycorset',
  'loubxbyy',
  'lochnessa93',
  'myla.feet',
  'electriclola',
  'whisperonascream',
  'nyxmonroe',
  'lylasbigheart',
  'jinjerspice',
  'womandrivenvip',
  'youkittenmexxx',
  'theonlybbystar',
  'levanabanana1',
  'sableheart',
  'alaska_kat',
  'kay_leo3',
  'barelyalex',
  'rubysroses',
  'tilly.fox',
  'ashleecat',
  'misshawthornvip',
  'catstaxxy',
  'mandymadisonxo',
  'candicedare',
  'emmberrosalyn',
  'themirandaaffect',
  'mollywinters',
  'cutepowerlegsvip',
  'cutepowerlegs',
  'miss_faith',
  'sirenaarlet',
  'phdprincess',
  'vanessastrawbe1',
  'honestlybecky_vip',
  'iwikteews',
  'nursebigbody',
  'sweetzie',
  'gracienextdoor',
  'mtkingandqueen',
  'catvondoubled',
  'princessdanniixxx',
  'lucylove-xoxo-vip',
  'cutiebooty.x',
  'longhairluna',
  'hellokittykutie',
  'veggiebabyyclips',
  'rileyroscato',
  'HoneyThorne',
  'araefitness',
  'milajoyce69',
  'MilaJoyce69',
  'curls.dasein',
  'Cherrylids',
  'isisxox',
  'laurenelizabeth',
  'finnyfansvip',
  'jennicalynn',
  'bunnycritter',
  'yorkshirestripper',
  'bjhouse',
  'ussbbwsupersoft',
  'sarahrae',
  'raecrush',
  'haze_lynn',
  'lyssjordan',
  'blxxdbunny',
  'bakedveggie',
  'little_red_doll',
  'wiscoswitchcouple',
  'meguthick',
  'RandomJocelyn',
  'farmerali',
  'mariahpinkitty',
  'princesst97',
  'aandjbabyyy',
  'jasmine-jizz',
  'lovebootystudio',
  'babygothipz',
  'curvyredhead89',
  'cur1ous.couple.420',
  'Cur1ouscoup420',
  'vidsbyvic',
  'rubysinclaire',
  'xoxokayla',
  'quinnnnx',
  'piercednoodle',
  'lunaroux',
  'mischagoeswild',
  'vipsage',
  'm0rninggl0ry',
  'nicolequinn',
  'NicoleQuinn',
  'artemisdune',
  'oliviauncovered',
  'bigbittyblaine',
  'kikiyou',
  'ashlaurenxxx',
  'mandymajestic',
  'sarahsota',
  'queenkayxox',
  'bigbellybeckyofficial',
  'smashmelllow',
  'thechubbs',
  'emmabttrfly',
  'juliette_rj',
  'onlylilac1',
  'lxves',
  'tayroseex',
  'fatcatter',
  'sofialovezxo',
  'bluntsandboobs',
  'cheeky_yelo',
  'bayleks',
  'whosmrandmrssmithvip',
  'lanareign',
  'LanaReign',
  'kactuskutieVIPee',
  'KactusKutie',
  'yourqueenkatiee',
  'skylarshark',
  'angelrat',
  'couple_of_perverts',
  'poesjenel',
  'undeadserana',
  'slimthickn',
  'Slimthickn',
  'celestialphoebe',
  'charlottethestallion',
  'goddessgabriela',
  'misstinytootsies',
  'lexiegrll',
  'tinsleyteaser',
  'katsoless',
  'naughtyshanti',
  'thefallenbabe',
  'TheFallenBabe',
  'thefallenbabepremium',
  'innocentfeetbabe',
  'sizeelevens',
  'JANDK92',
  'taylorcoo',
  'txhotwife84',
  'missstones',
  'soupygirl69',
  'chubby.hotgirl',
  'naughtynyxie',
  'aintnowifeyxoxo',
  'ellie_tease',
  'darlingsub',
  'nocarekali',
  'chubbyguati',
  'CaylaSnow',
  'caylasnow',
  'averygracex',
  'elly899',
  'reynalorenaaa',
  'Pandoradiorxoxo',
  'chubbybunniiix',
  'durdygirll',
  'onlyprincasspeach',
  'xCrybebi',
  'xcrybebi',
  'hotwife_alice',
  'softandpale',
  'cornbreadfedbabyyy',
  'kinkeeklown',
  'baby-bunny',
  'MyLeloo',
  'sexyirish83',
  'TheNeighborGirl',
  'Handjobs_teens',
  'xangelxfacexx',
  'valentinarosa89',
  'misslittlefoot4',
  'ashtonfaye',
  'SexySmoak',
  'Raydirin',
  'lisaevans',
  'okaykaylakay',
  'josiejaxxon',
  'narratophile',
  'catswetdream',
  'MiaSinner',
  'lilymichi',
  'rawfldn',
  'chloethewife',
  'f1lthyfucktoy',
  'stephinspace',
  'photo_misc',
  'jessieandjackson',
  'tinniangel_vip',
  'trisswitch',
  'cherrylovebombb',
  'diana1311sweetpussy',
  'kerolaychaves',
  'have-some-fun',
  'woodsnymphvip',
  'katiecooper4',
  'kittybrat13',
  'peachnecctar',
  'CeeAnna',
  'skyhighsierravip',
  'emmalilly',
  'SecretWifeyBabe',
  'sybianwife',
  'creampiehigh',
  'Mounting_Myrtle',
  'grazigoddess',
  'beautyandthefeet13',
  'ivorysoles',
  'kinky_mistress2021',
  'adorezee',
  'lilianafenty',
  'ashleylottsxo',
  'solelydawn',
  'lehlani',
  'fantasyfootjobs',
  'toetallydevine',
  'nikkisoless',
  'theasianarches',
  'AshCatTheCutie',
  'justinemarie196',
  'bgkerix38652',
  'babybear1211.vip',
  'theheavenlyterp',
  'ask7474747',
  'Ginger_Peach',
  'ciricesinsss',
  'bootynbodyqueen',
  'jadekennedypdx',
  'ashleespencer',
  'stina_kye',
  'theladyleanne',
  'nina.parker',
  'miafoster',
  'thevanessalovell',
  'bbjademoon',
  'sienna_june',
  'bowtienecklace',
  'jennacitrus',
  'kiki_me_please',
  'hotmomnexxxtdoor',
  'bobbiesweets',
  'erikakaysensuality',
  'sunnysunrayss',
  'anna_bianca',
  'fatbratfreya',
  'missfloraberlin',
  'peachpwuppy',
  'blondieblooms',
  'BlondieBlooms',
  'laulalalaaa',
  'goddessmona_91',
  'lovenataliefox',
  'nataliefox',
  'Felranna',
  'moodyfeet',
  'cookiesbby',
  'lenas-diary',
  'dafootgoddess1',
  'violettevaine',
  'neolasoles',
  'fetishmachinefemme',
  'egyalvip',
  'solepurposetexasofficial',
  'kikaboo2',
  'queengsoles',
  'celestialtootsies',
  'soleful_barbie',
  'vegan_footqueen',
  'miss.alexis.vip',
  'mistressmoria',
  'penelopestootsies739',
  'BabyBeeBub',
  'babybeebub',
  'nirvy',
  'sour.noodles',
  'aphroditepaws',
  'thetinyfeettreatvip',
  'mssjada',
  'prettylittlef33t57',
  'sweetpeacheslanevip',
  'OpheliaC',
  'opheliaopal420',
  'goddess.ophelia',
  'purgatorypup',
  'anastasiaysuamorleo',
  'esthererotica',
  'baebaezoe',
  'twopeacockprod',
  'meliszarah',
  'whor3fordaddy',
  'masmr',
  'mythicmaggie',
  'xomistressmandi',
  'sizetensolemates',
  'taystoes',
  'myposedtoesvip',
  'kiki_kitsune',
  'sugary.sole',
  'gracefulgracexo',
  'callmepurr',
  'thefantasychest',
  'super_soles',
  'hang10toess',
  'goddessfierce',
  'sevenandeleven',
  'emmyfeetandsocks',
  'honey.bee.feet',
  'miss-zelda',
  'remains0ftheday',
  'Remains0ftheday',
  'amadani',
  'Amadani',
  'islandboyvip',
  'hotyogawife',
  'zanewalker',
  'sage_roux',
  'sincityswingers',
  'emma_paige26',
  'hotwifestormx',
  'ichigoemma',
  'drewandelena',
  'mandymileena',
  'hotwifeaf',
  'little-red-ivy',
  'bi_sexualmilf',
  'theshortandinked1',
  'lupeandmicha',
  'waterbearerlovevip',
  'ukhotwifecouple',
  'heyhazel_x',
  'mander_of',
  'katnipkitten',
  'auroraw',
  'trins_feet',
  'hellcatblondie',
  'callie_jay396',
  'hotwifelife869',
  'swingingset',
  'sweetvickievip',
  'sammi-starfish',
  'areallyweakguy',
  'lladventures',
  'mariahmoneybagsvip',
  'mariahmoneybags',
  'hotwifekk',
  'Hotwifekk',
  'realhotwife4u',
  'Realhotwife4u',
  'valentineb69',
  'hotwife_peaches',
  'gapegal',
  'VineeVino',
  'sinply_me',
  'veronicavansing',
  'arizonarosexx',
  'thebitchwife',
  'maskedmylfy',
  'bigdanny10',
  'hotwifeannabelle',
  'bbapplehoneybbw',
  'silkysolesyyc',
  'polysweet',
  'mrsamsterdam',
  'bipolykinky',
  'bisocallife1vip',
  'bisocallife1',
  'dakota.hotwife',
  'leaandbear',
  'summerrose69',
  'iamkatemarley',
  'doseofdoxyx',
  'Doseofdoxyx',
  'iamhelenaprice',
  'adreenacuckoldress',
  'anacondanoire',
  'ladyanacondahoa',
  'bella_winters',
  'kimswallows',
  'littlemouchette',
  'clarkandmartha',
  'mohotwife',
  'mooreerinxxx',
  'miaart96',
  'bisum',
  'Bisum',
  'ukadventurecouple',
  'theenglishrose3',
  'hollyhotwifevip',
  'scarlettvanwhite',
  'serenitycox',
  'Louiselalisa',
  'RedWillow9269',
  'chloeemae',
  'emilybellexx',
  'katkarmaorgasmic',
  'MichelleRayne',
  'mmfluvah',
  'mrshiddendesires',
  'princess-rae',
  'Princess-Rae',
  'theannabound',
  'TheAnnaBound',
  'kinklifecouple',
  'bbcqueenhotwife',
  'vegaslatinahotwife',
  'myarykerx',
  'MyaRyker',
  'polish_hotwife',
  'sadieandrewsvip',
  'funmum',
  'princessbibbly',
  'lilblairrose',
  'EmmaMilkyMilf',
  'SummerNAustin',
  'iworshipavaonyx',
  'gummyghostgirl',
  'boozygremlin',
  'redvixenpinup',
  'sugarf4iry',
  'Wellyslut',
  'EllieRoss',
  'SonyaVegas',
  'littlelaine',
  'apex_sg',
  'vsilverss',
  'internetth0tt',
  'envyanne',
  'candycrushgirl',
  'prosexx',
  'tiffanitime',
  'WillowMadison',
  'zoebytheriver',
  'GingerAleMILF',
  'aldanaweed',
  'mathema-kitten',
  'ceelcee',
  'CeelCee',
  'fityoginina',
  'DeviousAdorei',
  'misskakes92',
  'mommyaurorafiend',
  'MilkyEuroMom',
  'couple.nexxx.door',
  'Tiabalton',
  'tarathewitch',
  'tinytoni',
  'nchotwife_vip',
  'cuckhungrywife',
  'milkykate',
  'elizabeth88',
  'Queenofmilk',
  'cuffsandbunnies',
  'PosyaFlowerCake',
  'alexxa_fire',
  'duncansaintxxx',
  'shycutie',
  'honeymomo',
  'tinyvampfangs',
  'morelunalotton',
  'katieslilwrld',
  'prettyy_allyy',
  'MrsLockhart',
  'AvroraLilWitch',
  'grannyswissss',
  'mandyfrizzle',
  'MandyFrizzle',
  'naughtymilfjoci',
  'innocenthotwifexxx',
  'innocenthotwife',
  'TheFunMilf',
  'Kassiopeia1',
  'dulcenalgass',
  'dulcenalgass2',
  'Dulcenalgass',
  'gingerrosecutie',
  'GingerRose',
  'sidneylong2',
  'allynicole917',
  'Fairymilkyluu',
  'KriisKriis',
  'EllieRenee',
  'josiejaxxonvip',
  'dhelene',
];

export const creatorPosts: CreatorPostDto[] = [
  {
    id: '926815284',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '*Car Sex, Anal, Facial!*\n\nRoad trips are more fun when you f..',
    content:
      '*Car Sex, Anal, Facial!*\n\nRoad trips are more fun when you fuck! Our friend drives while @taylormadexxx fucks me! I cream all over his big dick, he sticks it in my ass, then gives me a facial! We pulled into a gas station and my face was covered with cum!',
    embed: {},
    shared_file: false,
    added: '2024-03-24T13:59:13.929402',
    published: '2024-02-08T19:55:30',
    edited: null,
    file: {
      name: '0hmmou9ujla0ewdn1dec3_source.mp4',
      path: '/7c/30/7c307880c2005f1a9a1abff462025883fdad626eee0511f393d423363ac93f8b.mp4',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
  {
    id: '926810439',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '*Big Booty Lesbians*\n\nI know you like big booty tatted brune..',
    content:
      '*Big Booty Lesbians*\n\nI know you like big booty tatted brunettes.. how about TWO of them fucking each other?! Me and @xxirismaexx had so much fun eating each other’s pussies and sharing a double ended dildo. This is one of my favorite lesbian scenes ever!',
    embed: {},
    shared_file: false,
    added: '2024-03-24T14:06:31.654052',
    published: '2024-02-08T19:52:25',
    edited: null,
    file: {
      name: '0hmmopadn0c2mc0av5ac8_source.mp4',
      path: '/d4/52/d452d73dd42a1abc61bfb7e374e3d83739014f63f0e0a22f527402dab8a5e2d6.mp4',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
  {
    id: '926800227',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '*DP/DVP MFM Threesome!*\n\nThe day after @thecalideep fucked m..',
    content:
      '*DP/DVP MFM Threesome!*\n\nThe day after @thecalideep fucked my ass in front of hubby, he came back for round 2! This time we let @mrjaxxon join in on the fun! They spit roasted me, then filled my ass and pussy at the same time! I was so horny I even had them put both their cocks in my pussy at the same time. It was only the second time I had ever done DVP! Hubby gave me a facial and then Cali made me swallow his big load 😈',
    embed: {},
    shared_file: false,
    added: '2024-03-24T14:14:35.337633',
    published: '2024-02-08T19:46:30',
    edited: null,
    file: {
      name: '0hmmo9xoq35kth5l4w1vq_source.mp4',
      path: '/a5/1a/a51acadbaf218b7d16797133aa3ed8a405f45f9bd5c88a7068e80bf1ca5f8d28.mp4',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
  {
    id: '828203450',
    user: 'josiejaxxonvip',
    service: 'onlyfans',
    title: '',
    content: '',
    embed: {},
    shared_file: false,
    added: '2024-03-24T14:14:39.483702',
    published: '2023-11-29T13:47:28',
    edited: null,
    file: {
      name: '951x1207_4d22f8876ba45cc654dc53c3ae3881c0.jpg',
      path: '/23/0d/230d885837cd5cbb195ce8d7dfffe04a81d59fa394843f2cbe91456967226927.jpg',
    },
    attachments: [],
    poll: null,
    captions: null,
    tags: null,
  },
];
